# Default values for manticoresearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

balancer:
  runInterval: 5
  image:
    repository: registry.gitlab.com/manticoresearch/helm-charts/balancer
#    tag: 0.0.1
    pullPolicy: Always
  service:
    balancer:
      port: 9306
      targetPort: 9306
    observer:
      port: 8080
      targetPort: 8080
  config:
    path: /etc/manticoresearch/configmap.conf
    content: |
      searchd
      {
        listen = 9306:mysql41
        log = /var/log/manticore/searchd.log
        query_log = /var/log/manticore/query.log
        query_log_format = sphinxql
        pid_file = /var/run/manticore/searchd.pid
        binlog_path = /var/lib/manticore/data
      }


worker:
  replicaCount: 3
  clusterName: manticore
  image:
    repository: registry.gitlab.com/manticoresearch/helm-charts/worker
#    tag: 0.0.1
    pullPolicy: Always
  service:
    port: 9306
    targetPort: 9306
  volume:
    size: 1Gi
  config:
    path: /etc/manticoresearch/configmap.conf
    content: |
      searchd
      {
        listen = 9306:mysql41
        listen = 9301:mysql_vip
        listen = $ip:9312
        listen = $ip:9315-9415:replication
        binlog_path = /var/lib/manticore/data
        log = /var/lib/manticore/log/searchd.log
        query_log = /var/log/manticore/query.log
        query_log_format = sphinxql
        pid_file = /var/run/manticore/searchd.pid
        data_dir = /var/lib/manticore
        shutdown_timeout = 25s
      }

exporter:
  enabled: false
  image:
    repository: registry.gitlab.com/manticoresearch/helm-charts/exporter
    pullPolicy: Always
    tag: 0.0.1


imagePullSecrets: [name: registry-manticore]
nameOverride: ""
fullNameOverride: ""

serviceAccount:
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "manticore-sa"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000


resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
