apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "manticoresearch.serviceAccountName" . }}
  labels:
    {{- include "manticoresearch.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "manticoresearch.fullname" . }}
rules:
  - apiGroups: [ '' ]
    resources: [ 'configmaps','pods', 'services' ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ 'apps' ]
    resources: [ 'deployments', 'statefulsets' ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "manticoresearch.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "manticoresearch.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "manticoresearch.serviceAccountName" . }}
