apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "manticoresearch.fullname" . }}
  labels:
    {{- include "manticoresearch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "manticoresearch.selectorLabels" . | nindent 6 }}
  serviceName: m{{ STREAM_ID }}-balancer-manticore-svc
  template:
    metadata:
      {{ - with .Values.podAnnotations }}
      annotations:
        {{ - toYaml . | nindent 8 }}
      {{ - end }}
      labels:
        {{ - include "manticoresearch.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "manticoresearch.serviceAccountName" . }}
      {{ - with .Values.imagePullSecrets } }
      imagePullSecrets:
        {{ - toYaml . | nindent 8 }}
      {{ - end }}
      securityContext:
        {{ - toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: m{{ STREAM_ID }}-facade-manticore
        image: {{ Values.manticoreFacade.image.repository }}:{{ Values.manticoreFacade.image.tag }}
        imagePullPolicy: Always
        env:
          - name: LABEL
            value: "m{{ STREAM_ID }}"
        readinessProbe:
          tcpSocket:
            port: {{ Values.manticore.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: {{ Values.manticore.service.port }}
          initialDelaySeconds: 5
          periodSeconds: 3
