apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "manticoresearch.fullname" . }}-balancer
  labels:
    name: {{ include "manticoresearch.fullname" . }}-balancer
    {{- include "manticoresearch.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "manticoresearch.fullname" . }}-balancer
  serviceName: {{ include "manticoresearch.fullname" . }}-balancer-svc
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        name: {{ include "manticoresearch.fullname" . }}-balancer
        {{- include "manticoresearch.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "manticoresearch.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}-balancer
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.balancer.image.repository }}:{{ .Values.balancer.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.balancer.image.pullPolicy }}
        env:
          - name: WORKER_LABEL
            value: "{{ include "manticoresearch.fullname" . }}-worker"
          - name: CONFIGMAP_PATH
            value: {{ .Values.balancer.config.path }}
          - name: BALANCER_PORT
            value: "{{ .Values.balancer.service.balancer.port }}"
          - name: WORKER_PORT
            value: "{{ .Values.worker.service.port }}"
        readinessProbe:
          tcpSocket:
            port: {{ .Values.balancer.service.balancer.port }}
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: {{ .Values.balancer.service.balancer.port }}
          initialDelaySeconds: 5
          periodSeconds: 3
        volumeMounts:
          - name: config-volume
            mountPath: {{ .Values.balancer.config.path }}
            subPath: manticore.conf
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "manticoresearch.fullname" . }}-balancer-config
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
