apiVersion: v1
kind: ConfigMap
metadata:
  name: searchd-config
data:
  manticore.conf: |
    searchd
    {
      listen = 9306:mysql41
      log = /var/log/manticore/searchd.log
      query_log = /var/log/manticore/query.log
      query_log_format = sphinxql
      pid_file = /var/run/manticore/searchd.pid
      binlog_path = /var/lib/manticore/data
      max_packet_size = 128M
    }

