apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "balancer"
  labels:
    name: "balancer"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "balancer"
  serviceName: balancer-svc
  template:
    metadata:
      labels:
        name: "balancer"
    spec:
      serviceAccountName: manticore-sa
      imagePullSecrets:
        - name: registry-manticore
      containers:
      - name: balancer-manticore
        image: "registry.gitlab.com/manticoresearch/helm-charts/balancer:0.0.1"
        imagePullPolicy: Always
        env:
          - name: CONFIGMAP_PATH
            value: /etc/manticoresearch/manticore.conf
          - name: BALANCER_PORT
            value: "9306"
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
        readinessProbe:
          tcpSocket:
            port: 9306
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 9306
          initialDelaySeconds: 5
          periodSeconds: 3
        volumeMounts:
          - name: config-volume
            mountPath: /etc/manticoresearch/manticore.conf
            subPath: manticore.conf
      volumes:
        - name: config-volume
          configMap:
            name: searchd-config
