apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: "worker"
  labels:
    name: "worker"
spec:
  replicas: 1
  selector:
    matchLabels:
      name: "worker"
  serviceName: worker-svc
  template:
    metadata:
      labels:
        name: "worker"
        label: "manticore-worker"
    spec:
      serviceAccountName: manticore-sa
      imagePullSecrets:
        - name: registry-manticore
      containers:
      - name: worker-manticore
        image: "registry.gitlab.com/manticoresearch/helm-charts/worker:0.0.1"
        imagePullPolicy: Always
        env:
          - name: MANTICORE_PORT
            value: "9306"
          - name: CLUSTER_NAME
            value: "test_cluster"
          - name: BALANCER_URL
            value: "https://balancer-svc"
        readinessProbe:
          tcpSocket:
            port: 9306
          initialDelaySeconds: 5
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 9306
          initialDelaySeconds: 5
          periodSeconds: 3
        volumeMounts:
          - name: data
            mountPath: /var/lib/manticore/
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
