apiVersion: v1
kind: ServiceAccount
metadata:
  name: manticore-sa
  labels:
    name: manticore-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: manticore-role
rules:
  - apiGroups: [ '' ]
    resources: [ 'configmaps','pods', 'services' ]
    verbs: [ "get", "watch", "list" ]
  - apiGroups: [ 'apps' ]
    resources: [ 'deployments', 'statefulsets' ]
    verbs: [ "get", "watch", "list" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: manticore-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: manticore-role
subjects:
  - kind: ServiceAccount
    name: manticore-sa
